<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
        <StaticWebAssetProjectMode>Default</StaticWebAssetProjectMode>
        <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.8"/>
    </ItemGroup>

    <ItemGroup>
      <Content Update="Scripts/editor.js">
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
        <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\tools\DScratch.TreeVisualizers\DScratch.TreeVisualizers.csproj" />
      <ProjectReference Include="..\DScratch\DScratch.csproj" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="wwwroot\icons\format_bold.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\icons\format_color_fill.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\icons\format_color_reset.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\icons\format_h1.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\icons\format_h2.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\icons\format_h3.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\icons\format_h4.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\icons\format_h5.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\icons\format_h6.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\icons\format_italic.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\icons\format_paragraph.svg" />
    </ItemGroup>

    <Target Name="BundleJS" BeforeTargets="Build">
        <Exec Command="npm install" WorkingDirectory="BrowserInteractions/Scripts" />
        <Exec Command="npx esbuild editor.ts --bundle --outfile=../../wwwroot/js/editor.bundle.js" WorkingDirectory="BrowserInteractions/Scripts" />
    </Target>

</Project>
