using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace DScratch.SourceGenerator;

/// <summary>
/// A source generator that creates C# classes based on the schema.ts for ProseMirror.
/// </summary>
[Generator]
public class SourceGeneratorWithAdditionalFiles : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.AdditionalTextsProvider
            .Where(f => Path.GetFileName(f.Path) == "schema.ts")
            .Collect();

        context.RegisterSourceOutput(provider, GenerateCode);
    }

    private static void GenerateCode(SourceProductionContext context, ImmutableArray<AdditionalText> files)
    {
        var file = files.Single();

        var text = file.GetText(context.CancellationToken)?.ToString();
        if (text == null) return;

        var tokens = new Scanner(text).ScanTokens();
        var schemaDefinitionParts = new Parser(tokens).Parse();
        
        // Build up the source code.
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("namespace DScratch");
        sb.AppendLine("{");
        sb.AppendLine("public class PmSchema");
        sb.AppendLine("{");
        
        
        
        sb.AppendLine("}");
        sb.AppendLine("}");
        
        // Add the source code to the compilation.
        context.AddSource($"PmSchema.g.cs", sb.ToString());
    }
}